#func_print_head "Start the redis service"
#systemctl enable redis &>>${log_file}
#systemctl restart redis &>>${log_file}
#stat_check $?


- name: Setup a repo file
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: True

- name: Install Redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Update listen address - /etc/redis.conf
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Update listen address - /etc/redis/redis.conf
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start redis serivce
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes