- name: Configure yum repos for erlang
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/{{ item }}/script.rpm.sh | bash
  loop:
    - erlang
    - rabbitmq-server

- name: Install RabbitMQ
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Add application user
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('aws_ssm', 'roboshop.{{env}}.rabbitmq.amqp_user', region='us-east-1') }}"
    password: "{{ lookup('aws_ssm', 'roboshop.{{env}}.rabbitmq.amqp_pass', region='us-east-1') }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present



