
#    func_print_head "Create one user for the app and set permission\e[0m"
#    rabbitmqctl add_user roboshop ${roboshop_app_pwd} &>>${log_file} &>>${log_file}
#    rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" &>>${log_file}
#    stat_check $?

- name: Configure yum repos for erlang
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Configure YUM Repos for rabbitmq
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install RabbitMQ
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enable: yes

- name: Add application user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present



