- name: Load NodeJs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Load Mongodb Schema
  ansible.builtin.import_role:
    name: common
    tasks_from: mongo_schema_setup