- name: Add Application user
  ansible.builtin.user:
    name: roboshop

- name: Removing old app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory if it does not exist
  ansible.builtin.file:
    path: /app
    state: directory

#- name: Download the app code content and unzip
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: /app
#    remote_src: yes

- name: Download the app code content and unzip from nexus
  ansible.builtin.unarchive:
    src: http://172.31.92.253:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes
