- name: Install GoLang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App pre-req
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Download dependencies
  ansible.builtin.shell: go mod init ; go get ; go build
  args:
    chdir: /app

- name: Systemd setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

