#func_print_head "Installing Maven"
#yum install maven -y &>>${log_file}
#stat_check $?
#
#app_prereq
#func_print_head "Download the dependencies & build the application"
#mvn clean package &>>${log_file}
#mv target/${component}-1.0.jar ${component}.jar &>>${log_file}
#stat_check $?
#
#service_start
#mysql_schema_setup