- name: Install mysql client
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: Load schema
  ansible.builtin.shell: mysql -h roboshop.{{env}}.mysql.endpoint', region='us-east-1') }} -uroboshop.{{env}}.mysql.username', region='us-east-1') }} -proboshop.{{env}}.mysql.password', region='us-east-1') }} < /app/schema/{{ component }}.sql