- name: Configure nodejs repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App pre-req
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Load nodejs dependency
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Systemd setup
  ansible.builtin.import_tasks:
  args:
    chdir: /app


  #func_print_head "Download the dependencies"
  #npm install &>>${log_file}
  #stat_check $?
  #service_start